import: definition.yaml

concurrency:
  task:
    dbbench-std: 5
    os-std: 5
  agent:
    gpt-3.5-turbo-0613: 5

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - gpt-3.5-turbo-0613
    task:
      - dbbench-std
      - os-std

output: "outputs/{TIMESTAMP}"
