default:
  module: "src.server.tasks.knowledgegraph.KnowledgeGraph"
  parameters:
    round: 15
    sparql_url: "http://164.107.116.56:3093/sparql"

kg-dev:
  parameters:
    name: "KnowledgeGraph-dev"
    data_file: "data/knowledgegraph/dev.json"

kg-std:
  parameters:
    name: "KnowledgeGraph-std"
    data_file: "data/knowledgegraph/std.json"
